# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jingda Xu
email: xjd15076083141@gmail.com
birth: 1994.04.02
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1181631115763_.pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jingda Xu and I'm a NLP Researcher in Sogou Inc. (A Famous Internet company in China). 

  I have got my master's degree at Tianjin University (2019), China.

  I am skilled at Text Generation, Dialogue Systems and (Pretrain) Language Model and have great interest in Multimodal Understanding and Variation Models.


# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Customer Service Chatbot
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     # icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |  # this will include new lines to allow paragraphs
              - Since privatization deployment only supports c++, I reconstruct the original pipeline by using c++, including implying the CNN Siamese Network for both training and inference procedure, replacing the elasticsearch with faiss.
      
              - Since the real chat records are disordered (such as QQAQAA), I trained CNN Siamese Network for Question Answering and use it to reorder the chat records. 
      
              - Developed a pipeline to mine the dialogue template by representing chat records as graph and use graph-partition algorithm like Louvain or Infomap to find sub-template.
    # I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: left
        title: Speed Up Abstract Summarization Inference
        description: |  # this will include new lines to allow paragraphs
              
              - By analysing the computation details of T5, I reconstructed a more efficient T5 model. 
              - I also split the model to encoder, decoder_1 (for first step), decoder_2 (for subsequent steps) and use onnxruntime framework to speed up the inference. 
              - Through evaluation, I found that using greedy search doesn't affect the performance of system and can bring lots of time gains.
              - What's more, I devolep a computation graph optimization tool based on onnxgraph-surgeon provided by TensorRT to reduce the repeated shape inference for the variable in the onnx graph.
              - Using gpu-ngram blocking operator to replace the original ngram blocking which is in the cpu. 

      - layout: left
        title: Chinese WhiteList Ner
        # quote: >
        #   I research how to argument the ner performace by using the known entity list。
        description: |  # this will include new lines to allow paragraphs
              - I implemented an NER Baselines by using pytorch, include (LSTM+CRF, BERT+CRF, BERT+Softmax, MRC-NER, Span-NER).
              - I combine the span representation with entity embedding to improve the ner model performance.
              - I got competitive results in resume and Weibo dataset (For Weibo dataset, F1 0.72; For Resume dataset, F1 0.97).
      
      - layout: left
        title: Summarization Ability of Sogou Recording Pen
        # quote: >
        #   I research how to argument the ner performace by using the known entity list。
        description: |  # this will include new lines to allow paragraphs
              - I implemented extractive summarization models based on chinese word level XLNet (pre-trained by myself).
              - Since the extractive summarization can be seen as an unbalanced classification task, I use dice loss to alleviate the label unbalance and imporve the Rouge F1 over 1%.

      - layout: left
        title: NLP Common Packages
        # quote: >
        #   I research how to argument the ner performace by using the known entity list。
        description: |  # this will include new lines to allow paragraphs
              - I implemented and trained word level Chinese pre-training models (eg. BART, Albert, Bert, XLNet). Since the size of vocabulary is too big, I use adaptive embedding and adaptive softmax to reduce the model size.
              - Based on these pre-training models, I also provide API for some common tasks like data argument, punctation prediction. 

      - layout: left
        title: Table Reservation ChatBot
        # quote: >
        #   I research how to argument the ner performace by using the known entity list。
        description: |  # this will include new lines to allow paragraphs
              - I am responsible for the dialogue manager of the chatbot. By analysing the characteristics of the business, i design and devolop rule-based dialogue state tracker and dialogue policy. 
              - I am responsible for checking and maintaining the response pools.
              - By analysing the bad case, I optimize the dialogue policy.

      - layout: left
        title: Chatbot for Smart Earphones
        # quote: >
        #   I research how to argument the ner performace by using the known entity list。
        description: |  # this will include new lines to allow paragraphs
              - I develop the timming chatbot, alarm chatbot and book-keeping chatbot.  
              - I update Microsoft Recognizers Text (an universal named entity recognition library) by adding more patterns about time and money.
      
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Sogou Company
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2019 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I am an NLP Researcher in AI interaction department of Sogou. I have participated in some dialogue projects and now i am responsible for constructing AI ability in NLP (eg. Summarization, Named Entity Recognition). 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption:
        # quote: >
         Tianjin University  2016.09 - 2019.01  Computer Technology

      - layout: left
        # quote: >
        caption:
         Xiangtan University 2012.09 - 2016.06  Software Engineering
      
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP some of my other interests and hobbies are:
      - Basketball (I am a fan of Tmac and Harden.)
      - Traveling
      - Cooking
      - Photography (Fujifilm)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
